### ISSUE TITLE
Install Error - Indexing Failed

### ISSUE THREAD

**Issue by ric-evans** [abhishek72850/pyrock#17]
Upon installing the package, I immediately get the following error:
![image](https://github.com/abhishek72850/pyrock/assets/19216225/925a4e15-4fe1-4f90-9741-0fc3e8a3a410)

Here are my Python versions:
```
$ python -V
Python 2.7.18
                
$ python3 -V
Python 3.10.12
```

Thanks for your help, I'm looking forward to using PyRock.

**Comment by abhishekk72850** [comment]
What is the default python version?

It's not supported below py 3.8

**Comment by abhishek72850** [comment]
Great
